version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    stdin_open: true # Keep the container's STDIN open
    tty: true        # Allocate a pseudo-TTY
    environment:
      - MONGO_URI=mongodb://db:27017/tasks
    depends_on:
      - db

  db:
    image: mongo:6
    container_name: task-repo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: